stages:
    - deploy

# ---

deploy:image:
    before_script:
        - 'apk add --no-cache --no-progress ca-certificates curl'
    image:
        entrypoint: ['']
        name: alpine:latest
    only:
        - master
    script:
        - 'curl --request POST "https://cloud.docker.com/api/build/v1/source/11c3b5cc-cb52-46ab-a91a-559a42f333ad/trigger/${DOCKER_CLOUD_TOKEN}/call/"'
    stage: deploy
